import type { Metadata } from "next";
import "../../styles/index.css";
import Providers  from "../../providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  return (
    <html lang={locale}>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
